### ISSUE TITLE
Does not generate containers

### ISSUE THREAD

**Issue by Vladisl0ve** [nitupkcuf/ripper-wrapper#2]
That is the code of error:

os_x_ripper.sh: line 90: jq: command not found
(23) Failed writing body
os_x_ripper.sh: line 21: Docker: command not found
Mode is unset, setting to install runmode
Amount of containers not set, setting to maximum of 50
Starting ripper attack
**ERROR: In file './docker-compose.yml', service must be a mapping, not a NoneType.**

**Comment by huz7337** [comment]
+++

**Comment by huz7337** [comment]
please correct this so that we can continue our work

**Comment by Vladisl0ve** [comment]
> please correct this so that we can continue our work

Шчыра кажучы, я не зразумеў :D

**Comment by huz7337** [comment]
теж не працює

**Comment by Vladisl0ve** [comment]
> теж не працює

А, добра :D

Для тых, хто шарыць: я выдаліў старую версію ripper-wrapper, заінсталяваў новую і вось такую памылку атрымаў. 
Магло проста супасць, а магло і быць прычынаю памылкі.

**Comment by vinswanson** [comment]
@qmark @Vladisl0ve @huz7337 
You need to install jq first.

1)Link to Homebrew (easiest way to install jq) https://brew.sh
2) in terminal, run `brew install jq`
3) then `/bin/bash os_x_ripper.sh`

**Comment by Vladisl0ve** [comment]
> @qmark @Vladisl0ve @huz7337 You need to install jq first. How to fix:
> 
> 1. Link to Homebrew (package manager to install jq) https://brew.sh
>    1.1) In terminal run `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> 2. In terminal, run `brew install jq`
> 3. Then `/bin/bash os_x_ripper.sh`

Good job, works, thank you :)

P.s. Just type next commands (for Linux users):
1. `sudo snap install jq`
2. `sudo bash os_x_ripper.sh`

**Comment by qmark** [comment]
easier fix: https://github.com/nitupkcuf/ripper-wrapper/pull/7

**Comment by vinswanson** [comment]
In my case, it didn't work, for some reasons, so I sent alternative method (:
